### ISSUE TITLE
Testnet

### ISSUE THREAD

**Issue by AquiGorka** [dashpay/dash-roadmap#9]
Hello there, I am interested in integrating DASH into a universal wallet dapp I am working on, I could not find a testnet working insight-explorer that would broadcast my transactions.

Could you point me in the right direction?

Thanks!

**Comment by criskgl** [comment]
Sure wanna talk?

________________________________________________________________________________



2018-06-15 10:07 GMT-04:00 Gorka Ludlow <notifications@github.com>:

**Comment by nmarley** [comment]
@AquiGorka Hi, thanks for your interest in Dash. Our official company (Dash Core Group, Inc.) Insight deployment for testnet is found here: https://testnet-insight.dashevo.org/insight/

You can also set up your own instance by following the instructions here: https://github.com/dashevo/insight-ui

**Comment by AquiGorka** [comment]
@nmarley thanks! that's what I was looking for.

**Comment by AquiGorka** [comment]
FYI, thanks to your help I was able to include DASH into my `universal crypto wallet app`.
If you are interested: https://github.com/citrusbyte/universal-wallet
and a working `testnet` version: https://testnet.dirua.exchange/
